# Generated by Django 3.2.9 on 2021-11-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=20)),
                ('ano', models.CharField(max_length=20)),
                ('cor', models.CharField(max_length=20)),
                ('placa', models.CharField(max_length=20)),
            ],
        ),
    ]
