# Generated by Django 3.2.9 on 2021-11-18 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carro', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
    ]
