# Generated by Django 3.2.9 on 2021-11-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0002_carro_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
